import { Inter } from "next/font/google";
// import "./globals.css";
import Navbar from "@/app/components/navbar/navbar";
import Chatbot from "@/app/components/chatbot/Chatbot"; 
import "./temp.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Ensure to include the <head> tags for proper document structure */}
        <title>Master Lesesal</title>
      </head>
      <body className={inter.className + "items-center" }>
        <Navbar /> {/* This line includes the Navbar */}
        <div className={"items-center"}>
            <div className={"page-content "}>
                {children}
            </div>
        </div>
        <Chatbot /> 
      </body>
    </html>
  );
}
