import { Inter } from "next/font/google";
// import "./globals.css";
import Navbar from "@/app/components/navbar/navbar";
import "./temp.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Ensure to include the <head> tags for proper document structure */}
      </head>
      <body className={inter.className}>
        <Navbar /> {/* This line includes the Navbar */}
        {children}
      </body>
    </html>
  );
}
